### ISSUE TITLE
make yaml front matter compatible with other markdown based systems

### ISSUE THREAD

**Issue by aisbergde** [0xGG/crossnote-app#126]
the issue with the yaml front matter is the extra "note:", but I could imagine an option to avoid this "note:" to make it compatible to some other systems storing their metadata in yaml. 

Without this "note:" it would be nearly perfect. Al least for some common metadata like tags, createdAt, modifiedAt 

```yaml
---
note:
    createdAt: 2020-03-28T07:52:59.238Z
    modifiedAt: 2020-03-28T08:37:27.812Z
    tags: [tutorial]
    id: ""
---
```
